name = Sidebar
description = A single sidebar interior page 
template = sidebar-layout

; Regions
regions[branding] = Branding
regions[navigation] = Navigation Bar
regions[header] = Header
regions[hero] = Hero
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[sidebar_second] = Second Sidebar
regions[footer] = Footer 

; Styles
stylesheets[all][] = css/layouts/sidebar/sidebar.layout.css
stylesheets[all][] = css/layouts/sidebar/sidebar.layout.no-query.css