<?php
/**
 * @file
 * variable.field_bundle_settings_node__hero_slide.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'field_bundle_settings_node__hero_slide',
  'content' => array(
    'view_modes' => array(),
    'extra_fields' => array(
      'form' => array(
        'title' => array(
          'weight' => '-5',
        ),
        'path' => array(
          'weight' => '30',
        ),
      ),
      'display' => array(),
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
